# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# This file is based on Astropy's CI-helpers:
# https://github.com/astropy/ci-helpers

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      TEST_CMD: "python -m unittest discover --verbose"
      CONDA_DEPENDENCIES: "numpy scipy cython"
      PIP_DEPENDENCIES: "black"

  matrix:

        # Python 3.6
      - PYTHON_VERSION: "3.6"
        NUMPY_VERSION: "1.14"

      - PYTHON_VERSION: "3.6"
        NUMPY_VERSION: "1.15"

      - PYTHON_VERSION: "3.6"
        NUMPY_VERSION: "1.16"

        # Python 3.7
      - PYTHON_VERSION: "3.7"
        NUMPY_VERSION: "1.14"

      - PYTHON_VERSION: "3.7"
        NUMPY_VERSION: "1.15"

      - PYTHON_VERSION: "3.7"
        NUMPY_VERSION: "1.16"

matrix:
   fast_finish: true

platform:
    -x64

install:

    # Install Miniconda
    - "git clone . ci-helpers"
    - "powershell .appveyor/install-miniconda.ps1"

    # Set path again, need to find a way to avoid doing this again
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

    # Test that PATH is set correctly
    # Also show the numpy version
    - "conda --version"
    - "python --version"
    - "conda list --full-name numpy"

    # Cythonize
    # This also works if there are no cython extensions
    # so this is an insurance policy for the future
    - "python setup.py build_ext --inplace"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% %TEST_CMD%"

# Run the benchmarks
on_success:
  #- python -c "import npstreams; npstreams.benchmark()"